version: '3.8'

services:
  common_settings: &common-settings
    build:
      context: spark
      dockerfile: Dockerfile
    volumes:
      - ./data:/opt/spark/data/
      - ./src:/opt/spark/code/
  master:
    <<: *common-settings
    ports:
      - "4040:4040"
      - "8080:8080"
      - "7077:7077"
      - "15002:15002"
    container_name: spark-master-1